server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: dlyk-server

  # 配置数据库信息
  datasource:
    url: jdbc:mysql://192.168.3.44:3306/ddl_dlyk?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      # 最大连接数，默认10
      maximum-pool-size: 30
      # 最小连接数，默认10
      minimum-idle: 30
      # 等待连接池分配连接的最大市场，超过该时长还没有可用连接则发生超时异常（单位毫秒）
      connection-timeout: 5000
      # 空闲连接的最大时长，空闲多久就被释放回收，设置为0不让连接回收
      idle-timeout: 0
      # 一个连接的最大生命时间，超过该时间还没有使用就回收掉（单位毫秒），最好不要超过8小时
      max-lifetime: 18000000

  # 设置jackson返回json数据时，时区和格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 配置redis的连接信息
  data:
    redis:
      host: 192.168.3.44
      port: 6379
      password: 111111
      database: 0

# 配置mybatis信息
mybatis:
  type-aliases-package: com.ddl.entity
  mapper-locations: classpath:mapper/*.xml
