server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: dlyk-server

  # ???????
  datasource:
    url: jdbc:mysql://192.168.3.44:3306/ddl_dlyk?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      # ????????10
      maximum-pool-size: 30
      # ????????10
      minimum-idle: 30
      # ????????????????????????????????????????
      connection-timeout: 5000
      # ????????????????????????0??????
      idle-timeout: 0
      # ???????????????????????????????????????8??
      max-lifetime: 18000000

  # ??redis?????
  data:
    redis:
      host: 192.168.3.44
      port: 6379
      password: 111111
      database: 0

# ??mybatis??
mybatis:
  mapper-locations: classspath:mapper/*.xml
